version: '2'
services:
    db:
        container_name: db
        image: mariadb:latest
        volumes:
         - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: archondb
          MYSQL_USER: archon
          MYSQL_PASSWORD: password

    ArchonWeb:
        depends_on:
          - db
        container_name: ArchonWeb
        image: acastellano/archonweb:v3
        command: /docker-entrypoint.sh
        links: 
          - db
        ports:
          - "8080:80"
        restart: always
        environment:
          MYSQL_DATABASE: archondb
          MYSQL_USER: archon
          MYSQL_PASSWORD: password
          MYSQL_HOST: db
